// ============================================================================
// File: Services/AiProductContextService.cs
// Purpose:
//   Builds factual AI product context by combining ProductConfig with scraper
//   latest snapshot and compact history files, plus lightweight purchase/archive context. Suspicious/failed latest candidates are never used
//   as authoritative AI prices; the service falls back to accepted history until
//   the user confirms or manually resolves the price.
//
// Main functions:
//   - BuildAsync(productIds, token): returns normalized contexts for selected IDs.
//   - LoadHistoryAsync(token): loads compact history files listed in index.json.
//   - FindLatestProduct / FindHistoryProduct: match records by stable product ID.
//   - LoadAsync<T>(...): safely reads current-format JSON files.
//
// Inputs:
//   Product IDs, python/products.json through ProductConfigService, data/latest.json,
//   and compact data/history/*.json generated by the scraper.
//
// Outputs:
//   IReadOnlyList<AiProductContext> containing authoritative factual data for AI.
//   This service does not decide BUY/WAIT/NEUTRAL.
// ============================================================================

using System.Text.Json;
using System.Text.Json.Serialization;

using PriceWatch.Api.Models;

namespace PriceWatch.Api.Services;


public sealed class AiProductContextService
{
    private readonly AppPaths _paths;
    private readonly ProductConfigService _products;

    private static readonly JsonSerializerOptions JsonOptions = new();


    public AiProductContextService(
        AppPaths paths,
        ProductConfigService products
    )
    {
        _paths = paths;
        _products = products;
    }


    public async Task<IReadOnlyList<AiProductContext>> BuildAsync(
        IEnumerable<string> productIds,
        CancellationToken cancellationToken
    )
    {
        var ids = productIds
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (ids.Count == 0)
            return [];

        var configs = await _products.GetAllAsync();

        var selected = ids
            .Select(id =>
                configs.FirstOrDefault(product =>
                    string.Equals(
                        product.Id,
                        id,
                        StringComparison.OrdinalIgnoreCase
                    )
                )
                ?? throw new ArgumentException($"Product not found: {id}")
            )
            .ToList();

        var latest = await LoadAsync<LatestSnapshotFile>(
            _paths.LatestFile,
            cancellationToken
        );

        var historyFiles = await LoadHistoryAsync(cancellationToken);
        var result = new List<AiProductContext>();

        foreach (var config in selected)
        {
            var current = FindLatestProduct(
                latest?.Data,
                config.Id
            );

            var history = new List<AiPricePoint>();

            foreach (var snapshot in historyFiles)
            {
                var product = FindHistoryProduct(
                    snapshot.Data,
                    config.Id
                );

                // A successful scraper observation always has a current total/comparable
                // price. Unit price is optional and is attached to the same period.
                if (product?.CurrentPrice is not double price)
                    continue;

                history.Add(new AiPricePoint
                {
                    Date = snapshot.Period,
                    Price = price,
                    UnitPrice = product.CurrentUnitPrice,
                });
            }

            var prices = history
                .Select(item => item.Price)
                .ToList();

            var unitPrices = history
                .Where(item => item.UnitPrice is not null)
                .Select(item => item.UnitPrice!.Value)
                .ToList();

            var acceptedHistory = history
                .OrderByDescending(item => item.Date, StringComparer.Ordinal)
                .ToList();

            var currentIsAccepted = string.Equals(
                current?.Status,
                "success",
                StringComparison.OrdinalIgnoreCase
            );

            var safeCurrentPrice = currentIsAccepted
                ? current?.CurrentPrice
                : acceptedHistory.FirstOrDefault()?.Price;

            var safeCurrentUnitPrice = currentIsAccepted
                ? current?.CurrentUnitPrice
                : acceptedHistory.FirstOrDefault()?.UnitPrice;

            var safePreviousPrice = currentIsAccepted
                ? current?.PreviousPrice
                : acceptedHistory.Skip(1).FirstOrDefault()?.Price;

            var safePreviousUnitPrice = currentIsAccepted
                ? current?.PreviousUnitPrice
                : acceptedHistory
                    .Skip(1)
                    .FirstOrDefault(item => item.UnitPrice is not null)
                    ?.UnitPrice;

            result.Add(new AiProductContext
            {
                ProductId = config.Id,
                Name = config.Name,
                Currency = config.Currency,
                ComparisonQuantity = config.ComparisonQuantity,
                Unit = config.Unit,

                CurrentPrice = safeCurrentPrice,
                TargetPrice = config.TargetPrice,
                PreviousPrice = safePreviousPrice,
                HistoricalLow = MinOrFallback(prices, safeCurrentPrice),
                HistoricalHigh = MaxOrFallback(prices, safeCurrentPrice),
                HistoricalAverage = AverageOrFallback(prices, safeCurrentPrice),

                CurrentUnitPrice = safeCurrentUnitPrice,
                TargetUnitPrice = config.TargetUnitPrice,
                PreviousUnitPrice = safePreviousUnitPrice,
                HistoricalLowUnitPrice = MinOrFallback(
                    unitPrices,
                    safeCurrentUnitPrice
                ),
                HistoricalHighUnitPrice = MaxOrFallback(
                    unitPrices,
                    safeCurrentUnitPrice
                ),
                HistoricalAverageUnitPrice = AverageOrFallback(
                    unitPrices,
                    safeCurrentUnitPrice
                ),

                LastPurchasePrice = config.LastPurchasePrice,
                LastPurchaseDate = config.LastPurchaseDate,
                ArchivedAt = config.ArchivedAt,

                History = history,
            });
        }

        return result;
    }


    private async Task<List<PriceHistoryFile>> LoadHistoryAsync(
        CancellationToken cancellationToken
    )
    {
        var indexFile = Path.Combine(
            _paths.HistoryDirectory,
            "index.json"
        );

        var index = await LoadAsync<PriceHistoryIndex>(
            indexFile,
            cancellationToken
        );

        if (index?.Periods is null)
            return [];

        var result = new List<PriceHistoryFile>();

        foreach (var period in index.Periods)
        {
            if (
                string.IsNullOrWhiteSpace(period) ||
                Path.GetFileName(period) != period
            )
            {
                continue;
            }

            var path = Path.Combine(
                _paths.HistoryDirectory,
                $"{period}.json"
            );

            var snapshot = await LoadAsync<PriceHistoryFile>(
                path,
                cancellationToken
            );

            if (snapshot is null)
                continue;

            if (!string.Equals(
                snapshot.Period,
                period,
                StringComparison.Ordinal
            ))
            {
                continue;
            }

            result.Add(snapshot);
        }

        return result;
    }


    private static LatestSnapshotProduct? FindLatestProduct(
        IEnumerable<LatestSnapshotProduct>? products,
        string id
    )
    {
        if (products is null)
            return null;

        return products.FirstOrDefault(product =>
            string.Equals(
                product.ProductId,
                id,
                StringComparison.OrdinalIgnoreCase
            )
        );
    }


    private static PriceHistoryEntry? FindHistoryProduct(
        IEnumerable<PriceHistoryEntry>? products,
        string id
    )
    {
        if (products is null)
            return null;

        return products.FirstOrDefault(product =>
            string.Equals(
                product.ProductId,
                id,
                StringComparison.OrdinalIgnoreCase
            )
        );
    }


    private static double? MinOrFallback(
        IReadOnlyCollection<double> values,
        double? fallback
    ) => values.Count > 0 ? values.Min() : fallback;


    private static double? MaxOrFallback(
        IReadOnlyCollection<double> values,
        double? fallback
    ) => values.Count > 0 ? values.Max() : fallback;


    private static double? AverageOrFallback(
        IReadOnlyCollection<double> values,
        double? fallback
    ) => values.Count > 0 ? values.Average() : fallback;


    private static async Task<T?> LoadAsync<T>(
        string path,
        CancellationToken cancellationToken
    )
    {
        if (!File.Exists(path))
            return default;

        try
        {
            await using var stream = File.OpenRead(path);

            return await JsonSerializer.DeserializeAsync<T>(
                stream,
                JsonOptions,
                cancellationToken
            );
        }
        catch (JsonException)
        {
            return default;
        }
        catch (IOException)
        {
            return default;
        }
    }


    private sealed class LatestSnapshotFile
    {
        [JsonPropertyName("period")]
        [JsonRequired]
        public string Period { get; init; } = "";

        [JsonPropertyName("data")]
        [JsonRequired]
        public List<LatestSnapshotProduct> Data { get; init; } = [];
    }


    private sealed class LatestSnapshotProduct
    {
        [JsonPropertyName("product_id")]
        [JsonRequired]
        public string ProductId { get; init; } = "";

        [JsonPropertyName("status")]
        [JsonRequired]
        public string Status { get; init; } = "";

        [JsonPropertyName("current_price")]
        public double? CurrentPrice { get; init; }

        [JsonPropertyName("previous_price")]
        public double? PreviousPrice { get; init; }

        [JsonPropertyName("current_unit_price")]
        public double? CurrentUnitPrice { get; init; }

        [JsonPropertyName("previous_unit_price")]
        public double? PreviousUnitPrice { get; init; }
    }



}
