// ============================================================================
// File: Services/PriceReviewService.cs
// Purpose:
//   Accepts a scraper result that was deliberately classified as "suspicious".
//   Confirmation changes only the current/latest result and accepted history; it
//   does NOT disable scraping or write a permanent override into ProductConfig.
//   This lets a real price jump (for example a 90% discount ending) become the
//   new trusted baseline for future scraper validation.
//
// Main functions:
//   - AcceptSuspiciousPriceAsync(productId): confirm the detected candidate price.
//   - UpsertHistoryAsync(...): add/replace the confirmed product in its period.
//   - UpdateHistoryIndexAsync(period): keep history/index.json in sync.
//
// Inputs:
//   Product ID and the current data/latest.json generated by the scraper.
//
// Outputs:
//   The confirmed product JSON object. latest.json and the matching history
//   period are atomically updated with status="success" and review metadata.
// ============================================================================

using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace PriceWatch.Api.Services;


public sealed class PriceReviewService
{
    private readonly AppPaths _paths;
    private readonly SemaphoreSlim _writeLock = new(1, 1);

    private readonly JsonSerializerOptions _jsonOptions = new()
    {
        WriteIndented = true,
    };


    public PriceReviewService(AppPaths paths)
    {
        _paths = paths;
    }


    public async Task<JsonObject> AcceptSuspiciousPriceAsync(string productId)
    {
        if (string.IsNullOrWhiteSpace(productId))
        {
            throw new ArgumentException("Product ID is required.");
        }

        await _writeLock.WaitAsync();

        try
        {
            var latest = await ReadObjectAsync(_paths.LatestFile)
                ?? throw new InvalidOperationException(
                    "No latest scraper result is available."
                );

            var period = ReadString(latest, "period");

            if (string.IsNullOrWhiteSpace(period))
            {
                throw new InvalidOperationException(
                    "Latest scraper result has no history period."
                );
            }

            var data = latest["data"] as JsonArray
                ?? throw new InvalidOperationException(
                    "Latest scraper result has invalid product data."
                );

            var index = FindProductIndex(data, productId);

            if (index < 0)
            {
                throw new KeyNotFoundException("Product result not found.");
            }

            if (data[index] is not JsonObject current)
            {
                throw new InvalidOperationException(
                    "Latest product result is invalid."
                );
            }

            var status = ReadString(current, "status");

            if (!string.Equals(status, "suspicious", StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    "Only a suspicious price can be confirmed."
                );
            }

            var currentPrice = ReadNumber(current, "current_price");

            if (currentPrice is null || currentPrice <= 0)
            {
                throw new InvalidOperationException(
                    "The suspicious result does not contain a valid candidate price."
                );
            }

            var confirmed = (JsonObject)current.DeepClone();
            confirmed["status"] = "success";
            confirmed["error"] = null;
            confirmed["reviewed_by_user"] = true;
            confirmed["review_method"] = "confirmed";
            confirmed["reviewed_at"] = DateTimeOffset.Now.ToString("O");

            ApplyTargetState(confirmed);

            data[index] = confirmed;
            latest["generated_at"] = DateTimeOffset.Now.ToString("O");

            // Write the accepted history baseline first. If latest.json writing
            // were to fail afterwards, the operation can safely be retried and
            // the next scraper run will still use the confirmed price baseline.
            await UpsertHistoryAsync(period, confirmed);
            await UpdateHistoryIndexAsync(period);
            await WriteObjectAsync(_paths.LatestFile, latest);

            return confirmed;
        }
        finally
        {
            _writeLock.Release();
        }
    }


    private async Task UpsertHistoryAsync(
        string period,
        JsonObject confirmed
    )
    {
        var historyFile = Path.Combine(
            _paths.HistoryDirectory,
            $"{period}.json"
        );

        var history = await ReadObjectAsync(historyFile)
            ?? new JsonObject
            {
                ["period"] = period,
                ["generated_at"] = DateTimeOffset.Now.ToString("O"),
                ["data"] = new JsonArray(),
            };

        history["period"] = period;
        history["generated_at"] = DateTimeOffset.Now.ToString("O");

        if (history["data"] is not JsonArray data)
        {
            data = new JsonArray();
            history["data"] = data;
        }

        var productId = ReadString(confirmed, "product_id")
            ?? throw new InvalidOperationException(
                "Confirmed product has no product_id."
            );

        var index = FindProductIndex(data, productId);
        var historyCopy = (JsonObject)confirmed.DeepClone();

        if (index >= 0)
        {
            data[index] = historyCopy;
        }
        else
        {
            data.Add(historyCopy);
        }

        await WriteObjectAsync(historyFile, history);
    }


    private async Task UpdateHistoryIndexAsync(string period)
    {
        var indexFile = Path.Combine(
            _paths.HistoryDirectory,
            "index.json"
        );

        var root = await ReadObjectAsync(indexFile)
            ?? new JsonObject();

        var periods = root["periods"] as JsonArray ?? new JsonArray();
        var values = periods
            .Select(node => node?.GetValue<string>())
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Cast<string>()
            .ToHashSet(StringComparer.Ordinal);

        values.Add(period);

        var sortedPeriods = new JsonArray();

        foreach (var value in values.OrderByDescending(
            value => value,
            StringComparer.Ordinal
        ))
        {
            sortedPeriods.Add(value);
        }

        root["periods"] = sortedPeriods;
        await WriteObjectAsync(indexFile, root);
    }


    private static void ApplyTargetState(JsonObject product)
    {
        var currentPrice = ReadNumber(product, "current_price");
        var targetPrice = ReadNumber(product, "target_price");

        if (currentPrice is not null && targetPrice is not null)
        {
            product["below_target"] = currentPrice <= targetPrice;
            product["difference"] = Math.Round(
                currentPrice.Value - targetPrice.Value,
                2
            );
        }

        var currentUnitPrice = ReadNumber(product, "current_unit_price");
        var targetUnitPrice = ReadNumber(product, "target_unit_price");

        if (currentUnitPrice is not null && targetUnitPrice is not null)
        {
            product["unit_below_target"] = currentUnitPrice <= targetUnitPrice;
            product["unit_difference"] = Math.Round(
                currentUnitPrice.Value - targetUnitPrice.Value,
                4
            );
        }
    }


    private static int FindProductIndex(JsonArray data, string productId)
    {
        for (var index = 0; index < data.Count; index++)
        {
            if (data[index] is not JsonObject product)
            {
                continue;
            }

            var storedId = ReadString(product, "product_id");

            if (string.Equals(
                storedId,
                productId,
                StringComparison.OrdinalIgnoreCase
            ))
            {
                return index;
            }
        }

        return -1;
    }


    private async Task<JsonObject?> ReadObjectAsync(string filePath)
    {
        if (!File.Exists(filePath))
        {
            return null;
        }

        try
        {
            var json = await File.ReadAllTextAsync(filePath);
            return JsonNode.Parse(json) as JsonObject;
        }
        catch (JsonException exception)
        {
            throw new InvalidOperationException(
                $"Invalid JSON file: {filePath}",
                exception
            );
        }
    }


    private async Task WriteObjectAsync(string filePath, JsonObject value)
    {
        var directory = Path.GetDirectoryName(filePath)
            ?? throw new InvalidOperationException(
                "Unable to determine JSON output directory."
            );

        Directory.CreateDirectory(directory);

        var tempFile = filePath + ".tmp";
        var json = value.ToJsonString(_jsonOptions);

        try
        {
            await File.WriteAllTextAsync(
                tempFile,
                json + Environment.NewLine,
                new UTF8Encoding(false)
            );

            File.Move(tempFile, filePath, overwrite: true);
        }
        finally
        {
            if (File.Exists(tempFile))
            {
                File.Delete(tempFile);
            }
        }
    }


    private static string? ReadString(JsonObject value, string property)
    {
        return value[property] is JsonValue node &&
               node.TryGetValue<string>(out var result)
            ? result
            : null;
    }


    private static double? ReadNumber(JsonObject value, string property)
    {
        var node = value[property];

        if (node is null)
        {
            return null;
        }

        if (node is JsonValue jsonValue && jsonValue.TryGetValue<double>(out var number))
        {
            return number;
        }

        return double.TryParse(
            node.ToJsonString(),
            NumberStyles.Float,
            CultureInfo.InvariantCulture,
            out var parsed
        )
            ? parsed
            : null;
    }
}
