// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceWatch.Data;

#nullable disable

namespace PriceWatch.Data.Migrations
{
    [DbContext(typeof(PriceWatchDbContext))]
    [Migration("20260923135907_RemoveLastPurchaseFields")]
    partial class RemoveLastPurchaseFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceWatch.Data.Entities.ItemSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("default_quantity");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("ManualPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("manual_price");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("ScrapingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("scraping_enabled");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_item_sources");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_sources_item_id");

                    b.ToTable("item_sources", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.PriceAlertEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("PriceHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("price_history_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetUnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_unit_price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_price_alert_events");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_price_alert_events_item_id");

                    b.HasIndex("PriceHistoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_price_alert_events_price_history_id");

                    b.ToTable("price_alert_events", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origin");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long?>("ScrapeResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("scrape_result_id");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price")
                        .HasComputedColumnSql("price / quantity", true);

                    b.HasKey("Id")
                        .HasName("pk_price_history");

                    b.HasIndex("ScrapeResultId")
                        .IsUnique()
                        .HasDatabaseName("ix_price_history_scrape_result_id")
                        .HasFilter("scrape_result_id IS NOT NULL");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_price_history_source_id");

                    b.HasIndex("ItemId", "RecordedAt")
                        .HasDatabaseName("ix_price_history_item_id_recorded_at");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.ScrapeResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("ManualPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("manual_price");

                    b.Property<decimal?>("ManualQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("manual_quantity");

                    b.Property<decimal?>("ManualUnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("manual_unit_price")
                        .HasComputedColumnSql("CASE\r\n    WHEN manual_price IS NULL\r\n      OR manual_quantity IS NULL\r\n    THEN NULL\r\n    ELSE manual_price / manual_quantity\r\nEND", true);

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<decimal?>("ScrapedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("scraped_price");

                    b.Property<decimal?>("ScrapedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("scraped_quantity");

                    b.Property<decimal?>("ScrapedUnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("scraped_unit_price")
                        .HasComputedColumnSql("CASE\r\n    WHEN scraped_price IS NULL\r\n      OR scraped_quantity IS NULL\r\n    THEN NULL\r\n    ELSE scraped_price / scraped_quantity\r\nEND", true);

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SuspiciousReason")
                        .HasColumnType("text")
                        .HasColumnName("suspicious_reason");

                    b.HasKey("Id")
                        .HasName("pk_scrape_results");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_scrape_results_item_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_scrape_results_run_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_scrape_results_source_id");

                    b.HasIndex("ItemId", "ReviewStatus")
                        .HasDatabaseName("ix_scrape_results_item_id_review_status");

                    b.ToTable("scrape_results", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.ScrapeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Successful")
                        .HasColumnType("integer")
                        .HasColumnName("successful");

                    b.Property<int>("Suspicious")
                        .HasColumnType("integer")
                        .HasColumnName("suspicious");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id")
                        .HasName("pk_scrape_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_scrape_runs_started_at");

                    b.ToTable("scrape_runs", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.TrackedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int?>("CheckIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("check_interval_minutes");

                    b.Property<decimal>("ComparisonQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("comparison_quantity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<decimal?>("CurrentQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_quantity");

                    b.Property<long?>("CurrentSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_source_id");

                    b.Property<decimal?>("CurrentUnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("current_unit_price")
                        .HasComputedColumnSql("CASE\r\n    WHEN current_price IS NULL\r\n      OR current_quantity IS NULL\r\n    THEN NULL\r\n    ELSE current_price / current_quantity\r\nEND", true);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<DateTimeOffset?>("LastPriceChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_price_changed_at");

                    b.Property<DateTimeOffset?>("LastSuccessfulPriceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_price_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("previous_price");

                    b.Property<decimal?>("PreviousQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("previous_quantity");

                    b.Property<long?>("PreviousSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_source_id");

                    b.Property<decimal?>("PreviousUnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("previous_unit_price")
                        .HasComputedColumnSql("CASE\r\n    WHEN previous_price IS NULL\r\n      OR previous_quantity IS NULL\r\n    THEN NULL\r\n    ELSE previous_price / previous_quantity\r\nEND", true);

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_price");

                    b.Property<decimal?>("TargetUnitPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_unit_price")
                        .HasComputedColumnSql("CASE\r\n    WHEN target_price IS NULL\r\n    THEN NULL\r\n    ELSE target_price / comparison_quantity\r\nEND", true);

                    b.Property<bool>("TrackingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("tracking_enabled");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<string>("UpdateMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("update_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tracked_items");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("ix_tracked_items_archived_at");

                    b.HasIndex("CurrentSourceId")
                        .HasDatabaseName("ix_tracked_items_current_source_id");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_tracked_items_item_type");

                    b.HasIndex("PreviousSourceId")
                        .HasDatabaseName("ix_tracked_items_previous_source_id");

                    b.ToTable("tracked_items", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.ItemSource", b =>
                {
                    b.HasOne("PriceWatch.Data.Entities.TrackedItem", "Item")
                        .WithMany("Sources")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_sources_tracked_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.PriceAlertEvent", b =>
                {
                    b.HasOne("PriceWatch.Data.Entities.TrackedItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_alert_events_tracked_items_item_id");

                    b.HasOne("PriceWatch.Data.Entities.PriceHistory", "PriceHistory")
                        .WithMany()
                        .HasForeignKey("PriceHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_alert_events_price_history_price_history_id");

                    b.Navigation("Item");

                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.PriceHistory", b =>
                {
                    b.HasOne("PriceWatch.Data.Entities.TrackedItem", "Item")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_history_tracked_items_item_id");

                    b.HasOne("PriceWatch.Data.Entities.ScrapeResult", "ScrapeResult")
                        .WithMany()
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_price_history_scrape_results_scrape_result_id");

                    b.HasOne("PriceWatch.Data.Entities.ItemSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_price_history_item_sources_source_id");

                    b.Navigation("Item");

                    b.Navigation("ScrapeResult");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.ScrapeResult", b =>
                {
                    b.HasOne("PriceWatch.Data.Entities.TrackedItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrape_results_tracked_items_item_id");

                    b.HasOne("PriceWatch.Data.Entities.ScrapeRun", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrape_results_scrape_runs_run_id");

                    b.HasOne("PriceWatch.Data.Entities.ItemSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scrape_results_item_sources_source_id");

                    b.Navigation("Item");

                    b.Navigation("Run");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.TrackedItem", b =>
                {
                    b.HasOne("PriceWatch.Data.Entities.ItemSource", "CurrentSource")
                        .WithMany()
                        .HasForeignKey("CurrentSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tracked_items_item_sources_current_source_id");

                    b.HasOne("PriceWatch.Data.Entities.ItemSource", "PreviousSource")
                        .WithMany()
                        .HasForeignKey("PreviousSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tracked_items_item_sources_previous_source_id");

                    b.Navigation("CurrentSource");

                    b.Navigation("PreviousSource");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.ScrapeRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("PriceWatch.Data.Entities.TrackedItem", b =>
                {
                    b.Navigation("PriceHistory");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
