<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>PriceWatch-Private-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PriceWatch.Data\PriceWatch.Data.csproj" />
    <ProjectReference Include="..\PriceWatch.Core\PriceWatch.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content
      Include="..\..\scraper\**\*"
      Exclude="..\..\scraper\.venv\**;..\..\scraper\__pycache__\**;..\..\scraper\**\__pycache__\**;..\..\scraper\**\*.pyc"
      Link="scraper\%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
    />
  </ItemGroup>

</Project>